package com.winflag.libcollage.manager;

import androidx.core.view.PointerIconCompat;

import com.picspool.lib.collagelib.resource.collage.LibDMCollageInfo;
import com.winflag.libcollage.activity.BaseSdk;
import com.winflag.libcollage.resource.TemplateRes;
import java.util.ArrayList;
import java.util.List;


/* loaded from: classes.dex */
class CollageManager5 {
    CollageManager5() {
    }

    public static void fiveImageTpl(int i, int i2, int i3, List<TemplateRes> list) {
        ArrayList arrayList = new ArrayList();
        ArrayList arrayList2 = new ArrayList();
        arrayList2.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList2.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList2.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList2.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList.add(new LibDMCollageInfo(arrayList2, 10, i2, i));
        ArrayList arrayList3 = new ArrayList();
        arrayList3.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList3.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList3.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList3.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList.add(new LibDMCollageInfo(arrayList3, 10, i2, i));
        ArrayList arrayList4 = new ArrayList();
        arrayList4.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList4.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList4.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList4.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList.add(new LibDMCollageInfo(arrayList4, 10, i2, i));
        ArrayList arrayList5 = new ArrayList();
        arrayList5.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList5.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList5.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList5.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList.add(new LibDMCollageInfo(arrayList5, 10, i2, i));
        ArrayList arrayList6 = new ArrayList();
        arrayList6.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList6.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList6.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList6.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList.add(new LibDMCollageInfo(arrayList6, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_1", arrayList, i3, i2));
        ArrayList arrayList7 = new ArrayList();
        ArrayList arrayList8 = new ArrayList();
        arrayList8.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList8.add(CollageManagerUtils.initCollagePoint(1224, 0));
        arrayList8.add(CollageManagerUtils.initCollagePoint(1224, 1530));
        arrayList8.add(CollageManagerUtils.initCollagePoint(0, 1530));
        arrayList7.add(new LibDMCollageInfo(arrayList8, 10, i2, i));
        ArrayList arrayList9 = new ArrayList();
        arrayList9.add(CollageManagerUtils.initCollagePoint(0, 1530));
        arrayList9.add(CollageManagerUtils.initCollagePoint(1224, 1530));
        arrayList9.add(CollageManagerUtils.initCollagePoint(1224, 3060));
        arrayList9.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList7.add(new LibDMCollageInfo(arrayList9, 10, i2, i));
        ArrayList arrayList10 = new ArrayList();
        arrayList10.add(CollageManagerUtils.initCollagePoint(1224, 0));
        arrayList10.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList10.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList10.add(CollageManagerUtils.initCollagePoint(1224, PointerIconCompat.TYPE_GRAB));
        arrayList7.add(new LibDMCollageInfo(arrayList10, 10, i2, i));
        ArrayList arrayList11 = new ArrayList();
        arrayList11.add(CollageManagerUtils.initCollagePoint(1224, PointerIconCompat.TYPE_GRAB));
        arrayList11.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList11.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList11.add(CollageManagerUtils.initCollagePoint(1224, 2040));
        arrayList7.add(new LibDMCollageInfo(arrayList11, 10, i2, i));
        ArrayList arrayList12 = new ArrayList();
        arrayList12.add(CollageManagerUtils.initCollagePoint(1224, 2040));
        arrayList12.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList12.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList12.add(CollageManagerUtils.initCollagePoint(1224, 3060));
        arrayList7.add(new LibDMCollageInfo(arrayList12, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_2", arrayList7, i3, i2));
        ArrayList arrayList13 = new ArrayList();
        ArrayList arrayList14 = new ArrayList();
        arrayList14.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList14.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 0));
        arrayList14.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList14.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList13.add(new LibDMCollageInfo(arrayList14, 10, i2, i));
        ArrayList arrayList15 = new ArrayList();
        arrayList15.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 0));
        arrayList15.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList15.add(CollageManagerUtils.initCollagePoint(2040, 1530));
        arrayList15.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 1530));
        arrayList13.add(new LibDMCollageInfo(arrayList15, 10, i2, i));
        ArrayList arrayList16 = new ArrayList();
        arrayList16.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 1530));
        arrayList16.add(CollageManagerUtils.initCollagePoint(2040, 1530));
        arrayList16.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList16.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList13.add(new LibDMCollageInfo(arrayList16, 10, i2, i));
        ArrayList arrayList17 = new ArrayList();
        arrayList17.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList17.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList17.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList17.add(CollageManagerUtils.initCollagePoint(2040, 1530));
        arrayList13.add(new LibDMCollageInfo(arrayList17, 10, i2, i));
        ArrayList arrayList18 = new ArrayList();
        arrayList18.add(CollageManagerUtils.initCollagePoint(2040, 1530));
        arrayList18.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList18.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList18.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList13.add(new LibDMCollageInfo(arrayList18, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_10", arrayList13, i3, i2));
        ArrayList arrayList19 = new ArrayList();
        ArrayList arrayList20 = new ArrayList();
        arrayList20.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList20.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList20.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList20.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList19.add(new LibDMCollageInfo(arrayList20, 10, i2, i));
        ArrayList arrayList21 = new ArrayList();
        arrayList21.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList21.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList21.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList21.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList19.add(new LibDMCollageInfo(arrayList21, 10, i2, i));
        ArrayList arrayList22 = new ArrayList();
        arrayList22.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList22.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList22.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList22.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList19.add(new LibDMCollageInfo(arrayList22, 10, i2, i));
        ArrayList arrayList23 = new ArrayList();
        arrayList23.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList23.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList23.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList23.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList19.add(new LibDMCollageInfo(arrayList23, 10, i2, i));
        ArrayList arrayList24 = new ArrayList();
        arrayList24.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList24.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList24.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList24.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList19.add(new LibDMCollageInfo(arrayList24, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_16", arrayList19, i3, i2));
        ArrayList arrayList25 = new ArrayList();
        ArrayList arrayList26 = new ArrayList();
        arrayList26.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList26.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList26.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList26.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList25.add(new LibDMCollageInfo(arrayList26, 10, i2, i));
        ArrayList arrayList27 = new ArrayList();
        arrayList27.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList27.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList27.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList27.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList25.add(new LibDMCollageInfo(arrayList27, 10, i2, i));
        ArrayList arrayList28 = new ArrayList();
        arrayList28.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList28.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList28.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList28.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList25.add(new LibDMCollageInfo(arrayList28, 10, i2, i));
        ArrayList arrayList29 = new ArrayList();
        arrayList29.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList29.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList29.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList29.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList25.add(new LibDMCollageInfo(arrayList29, 10, i2, i));
        ArrayList arrayList30 = new ArrayList();
        arrayList30.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList30.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList30.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList30.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList25.add(new LibDMCollageInfo(arrayList30, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_5", arrayList25, i3, i2));
        ArrayList arrayList31 = new ArrayList();
        ArrayList arrayList32 = new ArrayList();
        arrayList32.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList32.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList32.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList32.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList31.add(new LibDMCollageInfo(arrayList32, 10, i2, i));
        ArrayList arrayList33 = new ArrayList();
        arrayList33.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList33.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList33.add(CollageManagerUtils.initCollagePoint(3060, 765));
        arrayList33.add(CollageManagerUtils.initCollagePoint(2040, 765));
        arrayList31.add(new LibDMCollageInfo(arrayList33, 10, i2, i));
        ArrayList arrayList34 = new ArrayList();
        arrayList34.add(CollageManagerUtils.initCollagePoint(2040, 765));
        arrayList34.add(CollageManagerUtils.initCollagePoint(3060, 765));
        arrayList34.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList34.add(CollageManagerUtils.initCollagePoint(2040, 1530));
        arrayList31.add(new LibDMCollageInfo(arrayList34, 10, i2, i));
        ArrayList arrayList35 = new ArrayList();
        arrayList35.add(CollageManagerUtils.initCollagePoint(2040, 1530));
        arrayList35.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList35.add(CollageManagerUtils.initCollagePoint(3060, 2295));
        arrayList35.add(CollageManagerUtils.initCollagePoint(2040, 2295));
        arrayList31.add(new LibDMCollageInfo(arrayList35, 10, i2, i));
        ArrayList arrayList36 = new ArrayList();
        arrayList36.add(CollageManagerUtils.initCollagePoint(2040, 2295));
        arrayList36.add(CollageManagerUtils.initCollagePoint(3060, 2295));
        arrayList36.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList36.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList31.add(new LibDMCollageInfo(arrayList36, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_6", arrayList31, i3, i2));
        ArrayList arrayList37 = new ArrayList();
        ArrayList arrayList38 = new ArrayList();
        arrayList38.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList38.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 0));
        arrayList38.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, PointerIconCompat.TYPE_GRAB));
        arrayList38.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList37.add(new LibDMCollageInfo(arrayList38, 10, i2, i));
        ArrayList arrayList39 = new ArrayList();
        arrayList39.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 0));
        arrayList39.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList39.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList39.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, PointerIconCompat.TYPE_GRAB));
        arrayList37.add(new LibDMCollageInfo(arrayList39, 10, i2, i));
        ArrayList arrayList40 = new ArrayList();
        arrayList40.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList40.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList40.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList40.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList37.add(new LibDMCollageInfo(arrayList40, 10, i2, i));
        ArrayList arrayList41 = new ArrayList();
        arrayList41.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList41.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList41.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList41.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList37.add(new LibDMCollageInfo(arrayList41, 10, i2, i));
        ArrayList arrayList42 = new ArrayList();
        arrayList42.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList42.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList42.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList42.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList37.add(new LibDMCollageInfo(arrayList42, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_3", arrayList37, i3, i2));
        ArrayList arrayList43 = new ArrayList();
        ArrayList arrayList44 = new ArrayList();
        arrayList44.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList44.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList44.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList44.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList43.add(new LibDMCollageInfo(arrayList44, 10, i2, i));
        ArrayList arrayList45 = new ArrayList();
        arrayList45.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList45.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList45.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList45.add(CollageManagerUtils.initCollagePoint(2040, PointerIconCompat.TYPE_GRAB));
        arrayList43.add(new LibDMCollageInfo(arrayList45, 10, i2, i));
        ArrayList arrayList46 = new ArrayList();
        arrayList46.add(CollageManagerUtils.initCollagePoint(2040, PointerIconCompat.TYPE_GRAB));
        arrayList46.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList46.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList46.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList43.add(new LibDMCollageInfo(arrayList46, 10, i2, i));
        ArrayList arrayList47 = new ArrayList();
        arrayList47.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList47.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList47.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList47.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList43.add(new LibDMCollageInfo(arrayList47, 10, i2, i));
        ArrayList arrayList48 = new ArrayList();
        arrayList48.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList48.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList48.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList48.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList43.add(new LibDMCollageInfo(arrayList48, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_7", arrayList43, i3, i2));
        ArrayList arrayList49 = new ArrayList();
        ArrayList arrayList50 = new ArrayList();
        arrayList50.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList50.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList50.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList50.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList49.add(new LibDMCollageInfo(arrayList50, 10, i2, i));
        ArrayList arrayList51 = new ArrayList();
        arrayList51.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList51.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, PointerIconCompat.TYPE_GRAB));
        arrayList51.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList51.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList49.add(new LibDMCollageInfo(arrayList51, 10, i2, i));
        ArrayList arrayList52 = new ArrayList();
        arrayList52.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, PointerIconCompat.TYPE_GRAB));
        arrayList52.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList52.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList52.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList49.add(new LibDMCollageInfo(arrayList52, 10, i2, i));
        ArrayList arrayList53 = new ArrayList();
        arrayList53.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList53.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList53.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList53.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList49.add(new LibDMCollageInfo(arrayList53, 10, i2, i));
        ArrayList arrayList54 = new ArrayList();
        arrayList54.add(CollageManagerUtils.initCollagePoint(2040, 2040));
        arrayList54.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList54.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList54.add(CollageManagerUtils.initCollagePoint(2040, 3060));
        arrayList49.add(new LibDMCollageInfo(arrayList54, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_8", arrayList49, i3, i2));
        ArrayList arrayList55 = new ArrayList();
        ArrayList arrayList56 = new ArrayList();
        arrayList56.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList56.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 0));
        arrayList56.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList56.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList55.add(new LibDMCollageInfo(arrayList56, 10, i2, i));
        ArrayList arrayList57 = new ArrayList();
        arrayList57.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList57.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 2040));
        arrayList57.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList57.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList55.add(new LibDMCollageInfo(arrayList57, 10, i2, i));
        ArrayList arrayList58 = new ArrayList();
        arrayList58.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 0));
        arrayList58.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList58.add(CollageManagerUtils.initCollagePoint(2040, PointerIconCompat.TYPE_GRAB));
        arrayList58.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, PointerIconCompat.TYPE_GRAB));
        arrayList55.add(new LibDMCollageInfo(arrayList58, 10, i2, i));
        ArrayList arrayList59 = new ArrayList();
        arrayList59.add(CollageManagerUtils.initCollagePoint(2040, 0));
        arrayList59.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList59.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList59.add(CollageManagerUtils.initCollagePoint(2040, PointerIconCompat.TYPE_GRAB));
        arrayList55.add(new LibDMCollageInfo(arrayList59, 10, i2, i));
        ArrayList arrayList60 = new ArrayList();
        arrayList60.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, PointerIconCompat.TYPE_GRAB));
        arrayList60.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList60.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList60.add(CollageManagerUtils.initCollagePoint(PointerIconCompat.TYPE_GRAB, 3060));
        arrayList55.add(new LibDMCollageInfo(arrayList60, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_15", arrayList55, i3, i2));
        ArrayList arrayList61 = new ArrayList();
        ArrayList arrayList62 = new ArrayList();
        arrayList62.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList62.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList62.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList62.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList61.add(new LibDMCollageInfo(arrayList62, 10, i2, i));
        ArrayList arrayList63 = new ArrayList();
        arrayList63.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList63.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList63.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList63.add(CollageManagerUtils.initCollagePoint(1530, PointerIconCompat.TYPE_GRAB));
        arrayList61.add(new LibDMCollageInfo(arrayList63, 10, i2, i));
        ArrayList arrayList64 = new ArrayList();
        arrayList64.add(CollageManagerUtils.initCollagePoint(0, PointerIconCompat.TYPE_GRAB));
        arrayList64.add(CollageManagerUtils.initCollagePoint(3060, PointerIconCompat.TYPE_GRAB));
        arrayList64.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList64.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList61.add(new LibDMCollageInfo(arrayList64, 10, i2, i));
        ArrayList arrayList65 = new ArrayList();
        arrayList65.add(CollageManagerUtils.initCollagePoint(0, 2040));
        arrayList65.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList65.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList65.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList61.add(new LibDMCollageInfo(arrayList65, 10, i2, i));
        ArrayList arrayList66 = new ArrayList();
        arrayList66.add(CollageManagerUtils.initCollagePoint(1530, 2040));
        arrayList66.add(CollageManagerUtils.initCollagePoint(3060, 2040));
        arrayList66.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList66.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList61.add(new LibDMCollageInfo(arrayList66, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_14", arrayList61, i3, i2));
        ArrayList arrayList67 = new ArrayList();
        ArrayList arrayList68 = new ArrayList();
        arrayList68.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList68.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList68.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList68.add(CollageManagerUtils.initCollagePoint(0, 1530));
        arrayList67.add(new LibDMCollageInfo(arrayList68, 10, i2, i, "template/mask/5/g_5_h/img1.png", BaseSdk.getContext()));
        ArrayList arrayList69 = new ArrayList();
        arrayList69.add(CollageManagerUtils.initCollagePoint(0, 1530));
        arrayList69.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList69.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList69.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList67.add(new LibDMCollageInfo(arrayList69, 10, i2, i, "template/mask/5/g_5_h/img4.png", BaseSdk.getContext()));
        ArrayList arrayList70 = new ArrayList();
        arrayList70.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList70.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList70.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList70.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList67.add(new LibDMCollageInfo(arrayList70, 10, i2, i, "template/mask/5/g_5_h/img2.png", BaseSdk.getContext()));
        ArrayList arrayList71 = new ArrayList();
        arrayList71.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList71.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList71.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList71.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList67.add(new LibDMCollageInfo(arrayList71, 10, i2, i, "template/mask/5/g_5_h/img3.png", BaseSdk.getContext()));
        ArrayList arrayList72 = new ArrayList();
        arrayList72.add(CollageManagerUtils.initCollagePoint(622, 764));
        arrayList72.add(CollageManagerUtils.initCollagePoint(2437, 764));
        arrayList72.add(CollageManagerUtils.initCollagePoint(2437, 2295));
        arrayList72.add(CollageManagerUtils.initCollagePoint(622, 2295));
        LibDMCollageInfo libDMCollageInfo = new LibDMCollageInfo(arrayList72, 10, i2, i, "template/mask/5/g_5_h/img5.png", BaseSdk.getContext());
        libDMCollageInfo.setIsCanCorner(false);
        arrayList67.add(libDMCollageInfo);
        list.add(CollageManagerUtils.initAssetItem("g5_n_0", arrayList67, i3, 0));
        ArrayList arrayList73 = new ArrayList();
        ArrayList arrayList74 = new ArrayList();
        arrayList74.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList74.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList74.add(CollageManagerUtils.initCollagePoint(2123, 935));
        arrayList74.add(CollageManagerUtils.initCollagePoint(934, 935));
        arrayList73.add(new LibDMCollageInfo(arrayList74, 0, i2, i2, "template/mask/5/g5_n_3/1.png", BaseSdk.getContext()));
        ArrayList arrayList75 = new ArrayList();
        arrayList75.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList75.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList75.add(CollageManagerUtils.initCollagePoint(2123, 2124));
        arrayList75.add(CollageManagerUtils.initCollagePoint(2122, 934));
        arrayList73.add(new LibDMCollageInfo(arrayList75, 0, i2, i2, "template/mask/5/g5_n_3/2.png", BaseSdk.getContext()));
        ArrayList arrayList76 = new ArrayList();
        arrayList76.add(CollageManagerUtils.initCollagePoint(934, 2123));
        arrayList76.add(CollageManagerUtils.initCollagePoint(2125, 2123));
        arrayList76.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList76.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList73.add(new LibDMCollageInfo(arrayList76, 0, i2, i2, "template/mask/5/g5_n_3/4.png", BaseSdk.getContext()));
        ArrayList arrayList77 = new ArrayList();
        arrayList77.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList77.add(CollageManagerUtils.initCollagePoint(937, 935));
        arrayList77.add(CollageManagerUtils.initCollagePoint(937, 2123));
        arrayList77.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList73.add(new LibDMCollageInfo(arrayList77, 0, i2, i2, "template/mask/5/g5_n_3/5.png", BaseSdk.getContext()));
        ArrayList arrayList78 = new ArrayList();
        arrayList78.add(CollageManagerUtils.initCollagePoint(689, 689));
        arrayList78.add(CollageManagerUtils.initCollagePoint(2372, 689));
        arrayList78.add(CollageManagerUtils.initCollagePoint(2372, 2372));
        arrayList78.add(CollageManagerUtils.initCollagePoint(689, 2372));
        LibDMCollageInfo libDMCollageInfo2 = new LibDMCollageInfo(arrayList78, 0, i2, i2, "template/mask/5/g5_n_3/3.png", BaseSdk.getContext());
        libDMCollageInfo2.setIsCanCorner(false);
        arrayList73.add(libDMCollageInfo2);
        list.add(CollageManagerUtils.initAssetItem("g5_n_3", arrayList73, i3, i2));
        ArrayList arrayList79 = new ArrayList();
        ArrayList arrayList80 = new ArrayList();
        arrayList80.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList80.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList80.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList80.add(CollageManagerUtils.initCollagePoint(0, 1530));
        arrayList79.add(new LibDMCollageInfo(arrayList80, 10, i2, i, "template/mask/5/g_5x/img2.png", BaseSdk.getContext()));
        ArrayList arrayList81 = new ArrayList();
        arrayList81.add(CollageManagerUtils.initCollagePoint(0, 1530));
        arrayList81.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList81.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList81.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList79.add(new LibDMCollageInfo(arrayList81, 10, i2, i, "template/mask/5/g_5x/img3.png", BaseSdk.getContext()));
        ArrayList arrayList82 = new ArrayList();
        arrayList82.add(CollageManagerUtils.initCollagePoint(1530, 0));
        arrayList82.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList82.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList82.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList79.add(new LibDMCollageInfo(arrayList82, 10, i2, i, "template/mask/5/g_5x/img4.png", BaseSdk.getContext()));
        ArrayList arrayList83 = new ArrayList();
        arrayList83.add(CollageManagerUtils.initCollagePoint(1530, 1530));
        arrayList83.add(CollageManagerUtils.initCollagePoint(3060, 1530));
        arrayList83.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList83.add(CollageManagerUtils.initCollagePoint(1530, 3060));
        arrayList79.add(new LibDMCollageInfo(arrayList83, 10, i2, i, "template/mask/5/g_5x/img5.png", BaseSdk.getContext()));
        ArrayList arrayList84 = new ArrayList();
        arrayList84.add(CollageManagerUtils.initCollagePoint(838, 838));
        arrayList84.add(CollageManagerUtils.initCollagePoint(2222, 838));
        arrayList84.add(CollageManagerUtils.initCollagePoint(2222, 2222));
        arrayList84.add(CollageManagerUtils.initCollagePoint(838, 2222));
        LibDMCollageInfo libDMCollageInfo3 = new LibDMCollageInfo(arrayList84, 10, i2, i, "template/mask/mask_circle.png", BaseSdk.getContext());
        libDMCollageInfo3.setIsCanCorner(false);
        arrayList79.add(libDMCollageInfo3);
        list.add(CollageManagerUtils.initAssetItem("g5_n_1", arrayList79, i3, i2));
        ArrayList arrayList85 = new ArrayList();
        ArrayList arrayList86 = new ArrayList();
        arrayList86.add(CollageManagerUtils.initCollagePoint1024(0, 0));
        arrayList86.add(CollageManagerUtils.initCollagePoint1024(1024, 0));
        arrayList86.add(CollageManagerUtils.initCollagePoint1024(768, 256));
        arrayList86.add(CollageManagerUtils.initCollagePoint1024(256, 256));
        arrayList85.add(new LibDMCollageInfo(arrayList86, 10, i2, i));
        ArrayList arrayList87 = new ArrayList();
        arrayList87.add(CollageManagerUtils.initCollagePoint1024(0, 0));
        arrayList87.add(CollageManagerUtils.initCollagePoint1024(256, 256));
        arrayList87.add(CollageManagerUtils.initCollagePoint1024(256, 768));
        arrayList87.add(CollageManagerUtils.initCollagePoint1024(0, 1024));
        arrayList85.add(new LibDMCollageInfo(arrayList87, 10, i2, i));
        ArrayList arrayList88 = new ArrayList();
        arrayList88.add(CollageManagerUtils.initCollagePoint1024(1024, 0));
        arrayList88.add(CollageManagerUtils.initCollagePoint1024(1024, 1024));
        arrayList88.add(CollageManagerUtils.initCollagePoint1024(768, 768));
        arrayList88.add(CollageManagerUtils.initCollagePoint1024(768, 256));
        arrayList85.add(new LibDMCollageInfo(arrayList88, 10, i2, i));
        ArrayList arrayList89 = new ArrayList();
        arrayList89.add(CollageManagerUtils.initCollagePoint1024(256, 768));
        arrayList89.add(CollageManagerUtils.initCollagePoint1024(768, 768));
        arrayList89.add(CollageManagerUtils.initCollagePoint1024(1024, 1024));
        arrayList89.add(CollageManagerUtils.initCollagePoint1024(0, 1024));
        arrayList85.add(new LibDMCollageInfo(arrayList89, 10, i2, i));
        ArrayList arrayList90 = new ArrayList();
        arrayList90.add(CollageManagerUtils.initCollagePoint1024(256, 256));
        arrayList90.add(CollageManagerUtils.initCollagePoint1024(768, 256));
        arrayList90.add(CollageManagerUtils.initCollagePoint1024(768, 768));
        arrayList90.add(CollageManagerUtils.initCollagePoint1024(256, 768));
        arrayList85.add(new LibDMCollageInfo(arrayList90, 10, i2, i));
        list.add(CollageManagerUtils.initAssetItem("g5_n_2", arrayList85, i3, i2));
        ArrayList arrayList91 = new ArrayList();
        ArrayList arrayList92 = new ArrayList();
        arrayList92.add(CollageManagerUtils.initCollagePoint(0, 0));
        arrayList92.add(CollageManagerUtils.initCollagePoint(3060, 0));
        arrayList92.add(CollageManagerUtils.initCollagePoint(3060, 3060));
        arrayList92.add(CollageManagerUtils.initCollagePoint(0, 3060));
        arrayList91.add(new LibDMCollageInfo(arrayList92, i3, i2, i));
        ArrayList arrayList93 = new ArrayList();
        arrayList93.add(CollageManagerUtils.initCollagePoint(882, 849));
        arrayList93.add(CollageManagerUtils.initCollagePoint(1530, 201));
        arrayList93.add(CollageManagerUtils.initCollagePoint(2178, 849));
        arrayList93.add(CollageManagerUtils.initCollagePoint(1530, 1497));
        LibDMCollageInfo libDMCollageInfo4 = new LibDMCollageInfo(arrayList93, i3, i2, i);
        libDMCollageInfo4.setIsShowFrame(true);
        libDMCollageInfo4.setIsCanCorner(false);
        arrayList91.add(libDMCollageInfo4);
        ArrayList arrayList94 = new ArrayList();
        arrayList94.add(CollageManagerUtils.initCollagePoint(1563, 1530));
        arrayList94.add(CollageManagerUtils.initCollagePoint(2211, 882));
        arrayList94.add(CollageManagerUtils.initCollagePoint(2859, 1530));
        arrayList94.add(CollageManagerUtils.initCollagePoint(2211, 2178));
        LibDMCollageInfo libDMCollageInfo5 = new LibDMCollageInfo(arrayList94, 10, i2, i);
        libDMCollageInfo5.setIsShowFrame(true);
        libDMCollageInfo5.setIsCanCorner(false);
        arrayList91.add(libDMCollageInfo5);
        ArrayList arrayList95 = new ArrayList();
        arrayList95.add(CollageManagerUtils.initCollagePoint(882, 2211));
        arrayList95.add(CollageManagerUtils.initCollagePoint(1530, 1536));
        arrayList95.add(CollageManagerUtils.initCollagePoint(2178, 2211));
        arrayList95.add(CollageManagerUtils.initCollagePoint(1530, 2859));
        LibDMCollageInfo libDMCollageInfo6 = new LibDMCollageInfo(arrayList95, 10, i2, i);
        libDMCollageInfo6.setIsShowFrame(true);
        libDMCollageInfo6.setIsCanCorner(false);
        arrayList91.add(libDMCollageInfo6);
        ArrayList arrayList96 = new ArrayList();
        arrayList96.add(CollageManagerUtils.initCollagePoint(201, 1530));
        arrayList96.add(CollageManagerUtils.initCollagePoint(849, 882));
        arrayList96.add(CollageManagerUtils.initCollagePoint(1497, 1530));
        arrayList96.add(CollageManagerUtils.initCollagePoint(849, 2178));
        LibDMCollageInfo libDMCollageInfo7 = new LibDMCollageInfo(arrayList96, 10, i2, i);
        libDMCollageInfo7.setIsShowFrame(true);
        libDMCollageInfo7.setIsCanCorner(false);
        arrayList91.add(libDMCollageInfo7);
        list.add(CollageManagerUtils.initAssetItem("g5_n_4", arrayList91, i3, i2));
    }
}
